CREATE TABLE IF NOT EXISTS REQUESTER(
  REQUESTER_ID INT PRIMARY KEY,
   FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(100) NOT NULL ,
  PASSWORD VARCHAR(100) NOT NULL ,
  IS_APPROVER VARCHAR(10) 
	); 

CREATE TABLE IF NOT EXISTS LEAVE_DETAILS (
  REQUESTER_ID INT ,FOREIGN KEY (REQUESTER_ID) REFERENCES REQUESTER(REQUESTER_ID),
  BACKUP_ID INT, FOREIGN KEY (BACKUP_ID) REFERENCES REQUESTER(REQUESTER_ID),
  APPROVER_ID INT, FOREIGN KEY (APPROVER_ID)  REFERENCES REQUESTER(REQUESTER_ID),
  START_DATE DATE,
  END_DATE DATE,
  IS_APPROVED VARCHAR(10),
  APPROVER_COMMENTS VARCHAR(300)  
); 